### ISSUE TITLE
Build failures with GHC 8.2 and 8.4 in v0.3.8.1 and v0.3.8.2

### ISSUE THREAD

**Issue by sjakobi** [nikita-volkov/vector-builder#7]
See https://matrix.hackage.haskell.org/#/package/vector-builder.

```
library/VectorBuilder/Prelude.hs:34:1: error:
    Could not find module ‘Data.Functor.Contravariant’
    Use -v to see a list of the files searched for.
   |
34 | import Data.Functor.Contravariant as Exports
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

---

Nevertheless: Merry christmas! :)

**Comment by sjakobi** [comment]
v0.3.8.3 also fails to build with GHC 8.2.2:

```
library/VectorBuilder/Prelude.hs:2:5: error:
    Conflicting exports for ‘<>’:
       ‘module Exports’ exports ‘Exports.<>’
         imported from ‘Data.Monoid’ at library/VectorBuilder/Prelude.hs:37:1-42
       ‘module Exports’ exports ‘Exports.<>’
         imported from ‘Data.Semigroup’ at library/VectorBuilder/Prelude.hs:42:35-48
  |
2 |   ( module Exports,
  |     ^^^^^^^^^^^^^^
```

You may want to use CI to check compatibility with older GHC versions. I usually use `haskell-ci github`: https://github.com/haskell-CI/haskell-ci#readme

**Comment by sjakobi** [comment]
As a Hackage trustee, I have created some Hackage revisions that should prevent users from encountering these build errors. See e.g. https://hackage.haskell.org/package/vector-builder-0.3.8.3/revisions/.
